### PR TITLE
refactored filters, moved some logic into the model

### PR DESCRIPTION
**Pull request by zfrenchee**

### CODE REVIEW

**Comment by zfrenchee** [comment]
As you can see at the bottom of FilterView, two things still bug me: 

# using innerHTML feels like a security vulnerability to me, or at least bad code. Can we do better? 
# using the index is pretty hacky. Is there a better way?

**Comment by BSteephenson** [comment]
Suggestions
- rename selector and selected to something more obvious like tagClass and selectedClass
- do we really need to specify these classes every time we make a FilterView? Maybe have defaults for these values. Also have a default for OneAtATime. Make life easier

Avoiding .innerHTML
when making spans, give each a specific id
```
for tag in @Filter
     <span id = 'tag-#{tag.name}' class='#{@selector}'> .... </span>
     $('#tag-' + tag.name).click = changeSelectedFilter(@, tag.name)
```
^^ just psuedo code. What this is does is when you click on the tag, it calls changeSelectedFilter(name) where name is different for each tag

Other than slight clarifications, looks good to me (make sure everything works haha)

**Comment by zfrenchee** [comment]
So the issue with using something else than innerHTML is that jquery can't get id's with spaces in them or special characters. I tried using ids, but couldn't. I'm wondering if we should either give each tag a unique id, or something find some other way of going about this.

**Comment by BSteephenson** [comment]
It's not toooo hacky. It doesn't break anything. Seems like something to make better later.
Other than that, just add some comments or pick better variable names to make it stupid easy for someone to figure out what your code does. And defaults would make things prettier.

**Comment by zfrenchee** [comment]
The defaults thing makes even more of a mess =/ So I just punted on that. It's also kind of nice to have all that documentation for what's going on in the code I suppose?

**Comment by BSteephenson** [comment]
I'm confuzzled
You call  @ChgGroupFilters.selectTags(group.tags)
Where do you make a selectTags function?

**Comment by zfrenchee** [comment]
Nice catch. Looks like I managed to implement that in another branch. Why don't you add it to this PR, I guess? 

	selectTags: (tags) -> (@Filters.select (filter) -> filter.get('name') in tags).each (filter) -> filter.set({'active': true})

**Comment by BSteephenson** [comment]
Dont you have to rerender it then? Let's save this for later. You understand this part better than I do.

**Comment by zfrenchee** [comment]
I rebuilt it so that there's a listener to state change. If the model changes, that triggers a styling change.

**Pull request merged**
