### PR TITLE
Markdown enabled in descriptions for groups and events

### PR DESCRIPTION
**Pull request by BSteephenson**
Markdown good. More power to the users

### CODE REVIEW

**Comment by zfrenchee** [comment]
I'm not sure this is something we're going to merge, because although I too like markdown, I think we want to keep the descriptions simple and manageable. More specifically, we don't want the users to have too much power: we want to be able to fit their descriptions really easily inside whatever div we choose. 

Litmus test: Facebook event descriptions don't allow markdown. I think we should follow their lead. I'm willing to be convinced, but I don't think this is something we should go for.

**Comment by zfrenchee** [comment]
@lyra833 @acannistra what do you guys think?

**Comment by acannistra** [comment]
I'm supportive of a limited subset of markdown (posting links seems like a
good idea, for example), but I agree that it could make design a nightmare.

On Mon, Apr 13, 2015 at 8:47 PM, Alexander Lenail <notifications@github.com>
wrote:

> @lyra833 <https://github.com/lyra833> @acannistra
> <https://github.com/acannistra> what do you guys think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zfrenchee/Bluemoon/pull/36#issuecomment-92547745>.
>



-- 
Tony Cannistra
Computer Science and Biology
Tufts University 2015
http://anthonycannistra.com

**Comment by zfrenchee** [comment]
Links does seem like a good idea. 

I'm also not sure how many people know how to use markdown, and some might get confused if they start a sentence with a hashtag for some reason and get formatting instead.

**Comment by acannistra** [comment]
Yeah, didn't think about the hashtag thing. Ideally we'd have a wysiwyg editor, but that's too much for right now.

**Comment by zfrenchee** [comment]
Alright. This deserves more thought, but in the meantime we're going to close this PR (to potentially be reopened later)

**Pull request closed without merging**
