### PR TITLE
ignore sails.io.js for now. improves page load time

### PR DESCRIPTION
**Pull request by BSteephenson**
title says it all

### CODE REVIEW

**Comment by BSteephenson** [comment]
wait no
this doesnt delete the old one stupid git. hold on

**Comment by BSteephenson** [comment]
jk it's all good now

**Comment by zfrenchee** [comment]
Umm, instead of changing the name of the file, I'd rather comment it out from pipeline.js, where it's included in the build, if that's a thing we can do. Can you check if that's possible?

**Comment by zfrenchee** [comment]
Cool beans.

**Pull request merged**
