### PR TITLE
fixes bug where user could not login after logging out

### PR DESCRIPTION
**Pull request by BSteephenson**
Fixes first part of issue #40

### CODE REVIEW

**Comment by BSteephenson** [comment]
imma merge it's tiny

**Comment by zfrenchee** [comment]
Hey not sure this is the proper approach. Seems like you'll re-bind events, which gives us that RAM issue.

**Comment by zfrenchee** [comment]
Nvmd. If it's an issue, at least it isn't a regression. This is how I was doing it back in the day.

**Comment by BSteephenson** [comment]
```
	logout: -> 
		$.get '/logout', (res) => 
			$('.tl-nav-message, .tl-group-dropdown, .tl-event-dropdown').addClass('hidden')
			$('.tl-login-button').text('Login')
			@constructLogin()

```

That was what you had at 07c3c0f

**Comment by zfrenchee** [comment]
exactly. That means there might be a bug there. I think we'll have to go through later and untangle this. React probably solves this nicely, but I think we should stick with backbone for now.

**Pull request merged**
